In [2]:
import pandas as pd

In [3]:
f_df = pd.read_csv("function_test_3.csv")
f_df[f_df.dist<10]

    Unnamed: 0              name  dist  avg_cos_similarity  avg_grad_norm
0            0            G_test   0.1            0.000000   0.000000e+00
1            1         G_sigmoid   0.1            0.000000   0.000000e+00
2            2        G_relu_sum   0.1           -0.565593   2.102957e+05
3            3       G_relu_prod   0.1           -0.863512   4.898523e+21
4            4  G_relu_prod_1000   0.1           -0.868842   4.886994e+29
5            5   G_sigmoid_gates   0.1            0.000000   0.000000e+00
6            6            R_test   0.1            0.000000   0.000000e+00
7            7            G_test   1.1            0.047073   6.083186e-03
8            8         G_sigmoid   1.1            0.008741   1.031997e-03
9            9        G_relu_sum   1.1           -0.548284   2.102457e+05
10          10       G_relu_prod   1.1           -0.170782   6.786818e+21
11          11  G_relu_prod_1000   1.1           -0.208158   6.671908e+29
12          12   G_sigmoid_gates   1.1            0.000000   0.000000e+00
13          13            R_test   1.1            0.000000   0.000000e+00
14          14            G_test   2.1           -0.002355   1.106305e+01
15          15         G_sigmoid   2.1            0.101115   1.209477e+01
16          16        G_relu_sum   2.1           -0.499366   2.099634e+05
17          17       G_relu_prod   2.1            0.007859   1.039752e+26
18          18  G_relu_prod_1000   2.1           -0.092736   6.881674e+29
19          19   G_sigmoid_gates   2.1            0.000000   0.000000e+00
20          20            R_test   2.1            0.000000   0.000000e+00

Func test 3:
1.1 G_test and G_sigmoid are close, there's no norm because right config is found
2.1 G_sigmoid kind of faces the right way but not really, no strong resding. G_test is in wrong direction
R_test is always zero. G_sigmoid_gates does find value, g_sigmoid doesn't perform badly.
Relu sum is BIG but exact wrong direction

Reduce to G_sigmoid, G_sigmoid_gates. For now we can attempt to fritter with optimizer - see if there's a set of settings that work out here.

In [8]:
m_15_12_df = pd.read_csv("data_15_12/m_15_12")
m_15_12_df

   Unnamed: 0   k   d            g_name   count  performance
0           0  12  15            R_test  244060     0.993083
1           1  12  15            G_test  244060     0.993083
2           2  12  15         G_sigmoid  153408     0.624219
3           3  12  15        G_relu_sum  192162     0.781909
4           4  12  15       G_relu_prod       0     0.000000
5           5  12  15  G_relu_prod_1000       0     0.000000
6           6  12  15   G_sigmoid_gates  244060     0.993083