In [5]:
import networkx as nx
from itertools import product, combinations_with_replacement

def get_hypercube_edges(d):
    """Generates the full edge set of a d-dimensional {-1, 1}^d hypercube."""
    # Vertices are tuples of length d with values -1 and 1
    vertices = list(product([-1, 1], repeat=d))
    edges = []
    for i in range(len(vertices)):
        for j in range(i + 1, len(vertices)):
            # Edges exist between vertices differing by exactly one coordinate
            diff = sum(1 for x, y in zip(vertices[i], vertices[j]) if x != y)
            if diff == 1:
                edges.append(tuple([tuple(vertices[i]), tuple(vertices[j])]))
    return edges

import itertools


def get_vertex_set_from_edges(edge_set):
    s=set()
    for edge in edge_set:
        s.add(tuple(edge[0]))
        s.add(tuple(edge[1]))
    return s

def apply_permutation(vertex_set, p):
    d=len(p)
    return [[v[p[i]] for i in range(d)] for v in vertex_set]

def get_transform_v1_v2(v1, v2):
    diff_list = [v1[i] * v2[i] for i in range(len(v1))]
    return lambda v: [v[i] * diff_list[i] for i in range(len(v))]


def get_if_original_set(new_lists, old_set):
    for l in new_lists:
        if tuple(l) not in old_set:
            return False
    return True

def count_symmetries(vertex_set):
    sym = 0
    d = len(list(vertex_set)[0])
    vertex_set = list(set([tuple(v) for v in vertex_set]))
    for p in itertools.permutations(range(d)):
        list_00 = apply_permutation(vertex_set, p)
        v1 = list_00[0]
        for v in vertex_set:
            sign_map = get_transform_v1_v2(v1, v)
            list_01 = list(map(sign_map, list_00))
            sym+=get_if_original_set(list_01, vertex_set)
    return sym

#print(count_symmetries([[1,1,1]]))

print(count_symmetries([[1,1,1],[-1,1,1], [1,-1,1], [-1,-1,1]]))

8

In [32]:
#don't feel like transforming into torch and back rn

def for_loop_hyperplane_intersection(h, edge_subset):
    intersected_edges = []
    for v1, v2 in edge_subset:
        val1 = sum([h[i]*v1_val for i,v1_val in enumerate(v1)])-h[-1]
        val2 = sum([h[i]*v2_val for i,v2_val in enumerate(v2)])-h[-1]
        if val1*val2<0:
            intersected_edges.append(tuple([v1,v2]))
    return intersected_edges

In [3]:
from collections import Counter 

def deg_seq(edge_subset):
    v_degs = Counter()
    for v1,v2 in edge_subset:
        v_degs[v1]+=1
        v_degs[v2]+=1
    degs = Counter()
    for _, deg in v_degs.items():
        degs[deg]+=1
    return tuple([tuple([deg, deg_count]) for deg, deg_count in degs.items()])

In [20]:
import pandas as pd
import random, time

d=4

filename = f"symmetries_tracked_{d}.csv"

h_limit=10
b_limit=10

chance = .01

edge_set = set(get_hypercube_edges(d))
edges = len(edge_set)
rows=[]

i=0
next_i=1
for h_coef in combinations_with_replacement(range(h_limit),d):
    for b in range(b_limit):
        # i+=1
        # if i!=next_i:
        #     continue
        # else: 
        #     next_i += random.randint(10,100)
        
        plane = h_coef+tuple([b])
        t_s = time.time()
        print(f"doing {plane}")
        intersected_edges = set(for_loop_hyperplane_intersection(plane, edge_set))
        non_intersected_edges = edge_set.difference(intersected_edges)

        vertices_in = get_vertex_set_from_edges(intersected_edges)
        vertices_out = get_vertex_set_from_edges(non_intersected_edges)
        if len(vertices_in)==0:
            continue
        t_int = time.time()
        print(f"{t_int-t_s} to get intersected edges")
        row_data = {"hyperplane": tuple(plane),
                   "edges_cut": len(intersected_edges),
                   "edges_not_cut": edges-len(intersected_edges),
                   "symmetries_inside": count_symmetries(vertices_in),
                   "symmetries_outside": count_symmetries(vertices_out),
                   "struct_inside": deg_seq(intersected_edges), 
                   "struct_outside": deg_seq(non_intersected_edges)}
        print(f"{time.time()-t_int} to get symmetries")
        print(row_data)
        rows.append(row_data)

sym_df = pd.DataFrame(rows)
#sym_df.to_csv(filename)
sym_df.head()

doing (0, 0, 0, 0, 0)
doing (0, 0, 0, 0, 1)
doing (0, 0, 0, 0, 2)
doing (0, 0, 0, 0, 3)
doing (0, 0, 0, 0, 4)
doing (0, 0, 0, 0, 5)
doing (0, 0, 0, 0, 6)
doing (0, 0, 0, 0, 7)
doing (0, 0, 0, 0, 8)
doing (0, 0, 0, 0, 9)
doing (0, 0, 0, 1, 0)
0.00011777877807617188 to get intersected edges
0.014216899871826172 to get symmetries
{'hyperplane': (0, 0, 0, 1, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 1, 1)
doing (0, 0, 0, 1, 2)
doing (0, 0, 0, 1, 3)
doing (0, 0, 0, 1, 4)
doing (0, 0, 0, 1, 5)
doing (0, 0, 0, 1, 6)
doing (0, 0, 0, 1, 7)
doing (0, 0, 0, 1, 8)
doing (0, 0, 0, 1, 9)
doing (0, 0, 0, 2, 0)
4.649162292480469e-05 to get intersected edges
0.007804155349731445 to get symmetries
{'hyperplane': (0, 0, 0, 2, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 2, 1)
5.3882598876953125e-05 to get intersected edges
0.01121068000793457 to get symmetries
{'hyperplane': (0, 0, 0, 2, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 2, 2)
doing (0, 0, 0, 2, 3)
doing (0, 0, 0, 2, 4)
doing (0, 0, 0, 2, 5)
doing (0, 0, 0, 2, 6)
doing (0, 0, 0, 2, 7)
doing (0, 0, 0, 2, 8)
doing (0, 0, 0, 2, 9)
doing (0, 0, 0, 3, 0)
8.130073547363281e-05 to get intersected edges
0.007689476013183594 to get symmetries
{'hyperplane': (0, 0, 0, 3, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 3, 1)
8.726119995117188e-05 to get intersected edges
0.009285688400268555 to get symmetries
{'hyperplane': (0, 0, 0, 3, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 3, 2)
5.340576171875e-05 to get intersected edges
0.007873773574829102 to get symmetries
{'hyperplane': (0, 0, 0, 3, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 3, 3)
doing (0, 0, 0, 3, 4)
doing (0, 0, 0, 3, 5)
doing (0, 0, 0, 3, 6)
doing (0, 0, 0, 3, 7)
doing (0, 0, 0, 3, 8)
doing (0, 0, 0, 3, 9)
doing (0, 0, 0, 4, 0)
8.058547973632812e-05 to get intersected edges
0.007539272308349609 to get symmetries
{'hyperplane': (0, 0, 0, 4, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 4, 1)
5.698204040527344e-05 to get intersected edges
0.007632017135620117 to get symmetries
{'hyperplane': (0, 0, 0, 4, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 4, 2)
5.555152893066406e-05 to get intersected edges
0.0070307254791259766 to get symmetries
{'hyperplane': (0, 0, 0, 4, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 4, 3)
5.507469177246094e-05 to get intersected edges
0.007025957107543945 to get symmetries
{'hyperplane': (0, 0, 0, 4, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 4, 4)
doing (0, 0, 0, 4, 5)
doing (0, 0, 0, 4, 6)
doing (0, 0, 0, 4, 7)
doing (0, 0, 0, 4, 8)
doing (0, 0, 0, 4, 9)
doing (0, 0, 0, 5, 0)
4.649162292480469e-05 to get intersected edges
0.007695674896240234 to get symmetries
{'hyperplane': (0, 0, 0, 5, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 5, 1)
5.888938903808594e-05 to get intersected edges
0.006990909576416016 to get symmetries
{'hyperplane': (0, 0, 0, 5, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 5, 2)
7.009506225585938e-05 to get intersected edges
0.0075588226318359375 to get symmetries
{'hyperplane': (0, 0, 0, 5, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 5, 3)
5.793571472167969e-05 to get intersected edges
0.007253170013427734 to get symmetries
{'hyperplane': (0, 0, 0, 5, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 5, 4)
5.817413330078125e-05 to get intersected edges
0.007383108139038086 to get symmetries
{'hyperplane': (0, 0, 0, 5, 4), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 5, 5)
doing (0, 0, 0, 5, 6)
doing (0, 0, 0, 5, 7)
doing (0, 0, 0, 5, 8)
doing (0, 0, 0, 5, 9)
doing (0, 0, 0, 6, 0)
4.9591064453125e-05 to get intersected edges
0.007369041442871094 to get symmetries
{'hyperplane': (0, 0, 0, 6, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 6, 1)
5.936622619628906e-05 to get intersected edges
0.007154941558837891 to get symmetries
{'hyperplane': (0, 0, 0, 6, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 6, 2)
5.793571472167969e-05 to get intersected edges
0.007074832916259766 to get symmetries
{'hyperplane': (0, 0, 0, 6, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 6, 3)
5.459785461425781e-05 to get intersected edges
0.007521390914916992 to get symmetries
{'hyperplane': (0, 0, 0, 6, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 6, 4)
6.937980651855469e-05 to get intersected edges
0.0069713592529296875 to get symmetries
{'hyperplane': (0, 0, 0, 6, 4), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 6, 5)
5.316734313964844e-05 to get intersected edges
0.00713038444519043 to get symmetries
{'hyperplane': (0, 0, 0, 6, 5), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 6, 6)
doing (0, 0, 0, 6, 7)
doing (0, 0, 0, 6, 8)
doing (0, 0, 0, 6, 9)
doing (0, 0, 0, 7, 0)
4.9591064453125e-05 to get intersected edges
0.0073549747467041016 to get symmetries
{'hyperplane': (0, 0, 0, 7, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 1)
5.91278076171875e-05 to get intersected edges
0.007679939270019531 to get symmetries
{'hyperplane': (0, 0, 0, 7, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 2)
6.508827209472656e-05 to get intersected edges
0.007161378860473633 to get symmetries
{'hyperplane': (0, 0, 0, 7, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 3)
5.8650970458984375e-05 to get intersected edges
0.007357597351074219 to get symmetries
{'hyperplane': (0, 0, 0, 7, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 4)
5.91278076171875e-05 to get intersected edges
0.007117033004760742 to get symmetries
{'hyperplane': (0, 0, 0, 7, 4), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 5)
6.437301635742188e-05 to get intersected edges
0.00754857063293457 to get symmetries
{'hyperplane': (0, 0, 0, 7, 5), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 6)
5.602836608886719e-05 to get intersected edges
0.007932901382446289 to get symmetries
{'hyperplane': (0, 0, 0, 7, 6), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 7, 7)
doing (0, 0, 0, 7, 8)
doing (0, 0, 0, 7, 9)
doing (0, 0, 0, 8, 0)
0.00010156631469726562 to get intersected edges
0.007706165313720703 to get symmetries
{'hyperplane': (0, 0, 0, 8, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 1)
6.0558319091796875e-05 to get intersected edges
0.0072934627532958984 to get symmetries
{'hyperplane': (0, 0, 0, 8, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 2)
5.841255187988281e-05 to get intersected edges
0.008235692977905273 to get symmetries
{'hyperplane': (0, 0, 0, 8, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 3)
0.0001010894775390625 to get intersected edges
0.008371114730834961 to get symmetries
{'hyperplane': (0, 0, 0, 8, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 4)
6.365776062011719e-05 to get intersected edges
0.007354736328125 to get symmetries
{'hyperplane': (0, 0, 0, 8, 4), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 5)
5.841255187988281e-05 to get intersected edges
0.0074579715728759766 to get symmetries
{'hyperplane': (0, 0, 0, 8, 5), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 6)
5.9604644775390625e-05 to get intersected edges
0.007204294204711914 to get symmetries
{'hyperplane': (0, 0, 0, 8, 6), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 7)
5.936622619628906e-05 to get intersected edges
0.0071642398834228516 to get symmetries
{'hyperplane': (0, 0, 0, 8, 7), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 8, 8)
doing (0, 0, 0, 8, 9)
doing (0, 0, 0, 9, 0)
5.054473876953125e-05 to get intersected edges
0.007208824157714844 to get symmetries
{'hyperplane': (0, 0, 0, 9, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 1)
6.437301635742188e-05 to get intersected edges
0.007235527038574219 to get symmetries
{'hyperplane': (0, 0, 0, 9, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 2)
5.745887756347656e-05 to get intersected edges
0.007415294647216797 to get symmetries
{'hyperplane': (0, 0, 0, 9, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 3)
5.8650970458984375e-05 to get intersected edges
0.007149219512939453 to get symmetries
{'hyperplane': (0, 0, 0, 9, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 4)
5.4836273193359375e-05 to get intersected edges
0.007470607757568359 to get symmetries
{'hyperplane': (0, 0, 0, 9, 4), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 5)
5.984306335449219e-05 to get intersected edges
0.007300138473510742 to get symmetries
{'hyperplane': (0, 0, 0, 9, 5), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 6)
6.008148193359375e-05 to get intersected edges
0.007437944412231445 to get symmetries
{'hyperplane': (0, 0, 0, 9, 6), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 7)
6.031990051269531e-05 to get intersected edges
0.0072023868560791016 to get symmetries
{'hyperplane': (0, 0, 0, 9, 7), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 8)
7.700920104980469e-05 to get intersected edges
0.007607936859130859 to get symmetries
{'hyperplane': (0, 0, 0, 9, 8), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 0, 9, 9)
doing (0, 0, 1, 1, 0)
doing (0, 0, 1, 1, 1)
5.078315734863281e-05 to get intersected edges
0.004883766174316406 to get symmetries
{'hyperplane': (0, 0, 1, 1, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 16, 'symmetries_outside': 384, 'struct_inside': ((1, 8), (2, 4)), 'struct_outside': ((4, 4), (3, 8), (2, 4))}
doing (0, 0, 1, 1, 2)
doing (0, 0, 1, 1, 3)
doing (0, 0, 1, 1, 4)
doing (0, 0, 1, 1, 5)
doing (0, 0, 1, 1, 6)
doing (0, 0, 1, 1, 7)
doing (0, 0, 1, 1, 8)
doing (0, 0, 1, 1, 9)
doing (0, 0, 1, 2, 0)
4.100799560546875e-05 to get intersected edges
0.006731271743774414 to get symmetries
{'hyperplane': (0, 0, 1, 2, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 2, 1)
4.482269287109375e-05 to get intersected edges
0.004118204116821289 to get symmetries
{'hyperplane': (0, 0, 1, 2, 1), 'edges_cut': 4, 'edges_not_cut': 28, 'symmetries_inside': 48, 'symmetries_outside': 384, 'struct_inside': ((1, 8),), 'struct_outside': ((4, 8), (3, 8))}
doing (0, 0, 1, 2, 2)
4.6253204345703125e-05 to get intersected edges
0.005243062973022461 to get symmetries
{'hyperplane': (0, 0, 1, 2, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 16, 'symmetries_outside': 384, 'struct_inside': ((1, 8), (2, 4)), 'struct_outside': ((4, 4), (3, 8), (2, 4))}
doing (0, 0, 1, 2, 3)
doing (0, 0, 1, 2, 4)
doing (0, 0, 1, 2, 5)
doing (0, 0, 1, 2, 6)
doing (0, 0, 1, 2, 7)
doing (0, 0, 1, 2, 8)
doing (0, 0, 1, 2, 9)
doing (0, 0, 1, 3, 0)
4.482269287109375e-05 to get intersected edges
0.006610870361328125 to get symmetries
{'hyperplane': (0, 0, 1, 3, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 3, 1)
4.839897155761719e-05 to get intersected edges
0.00708770751953125 to get symmetries
{'hyperplane': (0, 0, 1, 3, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 3, 2)
5.1021575927734375e-05 to get intersected edges
0.004462003707885742 to get symmetries
{'hyperplane': (0, 0, 1, 3, 2), 'edges_cut': 4, 'edges_not_cut': 28, 'symmetries_inside': 48, 'symmetries_outside': 384, 'struct_inside': ((1, 8),), 'struct_outside': ((4, 8), (3, 8))}
doing (0, 0, 1, 3, 3)
5.078315734863281e-05 to get intersected edges
0.0049479007720947266 to get symmetries
{'hyperplane': (0, 0, 1, 3, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 16, 'symmetries_outside': 384, 'struct_inside': ((1, 8), (2, 4)), 'struct_outside': ((4, 4), (3, 8), (2, 4))}
doing (0, 0, 1, 3, 4)
doing (0, 0, 1, 3, 5)
doing (0, 0, 1, 3, 6)
doing (0, 0, 1, 3, 7)
doing (0, 0, 1, 3, 8)
doing (0, 0, 1, 3, 9)
doing (0, 0, 1, 4, 0)
4.3392181396484375e-05 to get intersected edges
0.006929636001586914 to get symmetries
{'hyperplane': (0, 0, 1, 4, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 4, 1)
5.2928924560546875e-05 to get intersected edges
0.006853580474853516 to get symmetries
{'hyperplane': (0, 0, 1, 4, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 4, 2)
5.340576171875e-05 to get intersected edges
0.007378816604614258 to get symmetries
{'hyperplane': (0, 0, 1, 4, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 4, 3)
5.53131103515625e-05 to get intersected edges
0.0041730403900146484 to get symmetries
{'hyperplane': (0, 0, 1, 4, 3), 'edges_cut': 4, 'edges_not_cut': 28, 'symmetries_inside': 48, 'symmetries_outside': 384, 'struct_inside': ((1, 8),), 'struct_outside': ((4, 8), (3, 8))}
doing (0, 0, 1, 4, 4)
7.534027099609375e-05 to get intersected edges
0.005469322204589844 to get symmetries
{'hyperplane': (0, 0, 1, 4, 4), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 16, 'symmetries_outside': 384, 'struct_inside': ((1, 8), (2, 4)), 'struct_outside': ((4, 4), (3, 8), (2, 4))}
doing (0, 0, 1, 4, 5)
doing (0, 0, 1, 4, 6)
doing (0, 0, 1, 4, 7)
doing (0, 0, 1, 4, 8)
doing (0, 0, 1, 4, 9)
doing (0, 0, 1, 5, 0)
4.506111145019531e-05 to get intersected edges
0.007870674133300781 to get symmetries
{'hyperplane': (0, 0, 1, 5, 0), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 5, 1)
5.269050598144531e-05 to get intersected edges
0.0069732666015625 to get symmetries
{'hyperplane': (0, 0, 1, 5, 1), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 5, 2)
5.5789947509765625e-05 to get intersected edges
0.011061906814575195 to get symmetries
{'hyperplane': (0, 0, 1, 5, 2), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 5, 3)
9.5367431640625e-05 to get intersected edges
0.008668899536132812 to get symmetries
{'hyperplane': (0, 0, 1, 5, 3), 'edges_cut': 8, 'edges_not_cut': 24, 'symmetries_inside': 384, 'symmetries_outside': 384, 'struct_inside': ((1, 16),), 'struct_outside': ((3, 16),)}
doing (0, 0, 1, 5, 4)
6.318092346191406e-05 to get intersected edges
0.004548072814941406 to get symmetries

,hyperplane,edges_cut,edges_not_cut,symmetries_inside,symmetries_outside,struct_inside,struct_outside
0,"(0, 0, 0, 1, 0)",8,24,384,384,"((1, 16),)","((3, 16),)"
1,"(0, 0, 0, 2, 0)",8,24,384,384,"((1, 16),)","((3, 16),)"
2,"(0, 0, 0, 2, 1)",8,24,384,384,"((1, 16),)","((3, 16),)"
3,"(0, 0, 0, 3, 0)",8,24,384,384,"((1, 16),)","((3, 16),)"
4,"(0, 0, 0, 3, 1)",8,24,384,384,"((1, 16),)","((3, 16),)"

In [8]:
sym_df["symmetries_inside"].unique()

array([384,  16,  48,   4,  12,  24,   2,   8,   6])

In [21]:
sym_df["symmetries_outside"].unique()

array([384,  24])

In [9]:
sym_df["struct_inside"].unique()

array([((1, 16),), ((1, 8), (2, 4)), ((1, 8),), ((1, 4), (2, 2)),
       ((2, 6), (1, 8)), ((1, 8), (2, 2)), ((1, 4),), ((2, 12),),
       ((2, 6), (1, 4)), ((1, 14),), ((1, 11), (2, 3), (3, 1)),
       ((1, 6), (3, 2)), ((1, 6), (2, 2)), ((2, 7), (1, 2)),
       ((1, 8), (2, 3)), ((1, 6), (2, 3)), ((2, 4), (1, 8)),
       ((2, 5), (3, 1), (1, 7)), ((1, 6), (2, 2), (3, 2)),
       ((2, 6), (1, 6), (3, 2)), ((1, 5), (3, 3), (2, 3)),
       ((1, 5), (2, 4), (3, 1)), ((2, 8), (3, 2), (1, 2)),
       ((2, 6), (3, 1), (1, 1)), ((2, 5), (3, 1), (1, 5)),
       ((1, 4), (3, 2), (2, 1)), ((1, 4), (4, 1)),
       ((2, 4), (1, 5), (3, 1)), ((2, 9), (1, 2)), ((2, 6), (3, 4)),
       ((2, 7), (3, 2)), ((2, 3), (1, 3), (3, 1))], dtype=object)

In [18]:
sym_df[sym_df["symmetries_inside"]>sym_df["symmetries_outside"]]

Empty DataFrame
Columns: [hyperplane, edges_cut, edges_not_cut, symmetries_inside, symmetries_outside, struct_inside, struct_outside]
Index: []

In [38]:
from itertools import chain, combinations

def powerset(iterable):
    """powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"""
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))

planes = [[1,1,1,3,3,-4,0],
                        [-2,-2,-2,3,3,-1,0],
                        [3,3,3,1,1,-4,0],
                        [-1,-1,-1,3,3,6,0],
                        [3,3,3,1,1,8,0]]
edge_set = set(get_hypercube_edges(len(planes[0])-1))
for p in planes:
    
    intersected_edges = for_loop_hyperplane_intersection(p, edge_set)
    print(len(intersected_edges))

for p_list in powerset(planes):
    print(len(p_list), " planes")
    print(p_list)
    intersected_edges = set()
    for p in p_list:
        intersected_edges = intersected_edges.union(set(for_loop_hyperplane_intersection(p, edge_set)))
    
    non_intersected_edges = edge_set.difference(intersected_edges)

    vertices_in = get_vertex_set_from_edges(intersected_edges)
    vertices_out = get_vertex_set_from_edges(non_intersected_edges)
    if len(vertices_in)==0:
        continue
    t_int = time.time()
    print(f"{t_int-t_s} to get intersected edges")
    row_data = {"edges_cut": len(intersected_edges),
               "edges_not_cut": edges-len(intersected_edges),
               "symmetries_inside": count_symmetries(vertices_in),
               "symmetries_outside": count_symmetries(vertices_out),
               "struct_inside": deg_seq(intersected_edges), 
               "struct_outside": deg_seq(non_intersected_edges)}
    print(f"{time.time()-t_int} to get symmetries")
    print(row_data)
    rows.append(row_data)

52
60
60
52
48
0  planes
()
1  planes
([1, 1, 1, 3, 3, -4, 0],)
3766.463777780533 to get intersected edges
4.117760181427002 to get symmetries
{'edges_cut': 52, 'edges_not_cut': -20, 'symmetries_inside': 72, 'symmetries_outside': 46080, 'struct_inside': ((3, 6), (4, 2), (2, 36), (1, 6)), 'struct_outside': ((6, 14), (4, 36), (5, 6), (3, 6), (2, 2))}
1  planes
([-2, -2, -2, 3, 3, -1, 0],)
3770.58193731308 to get intersected edges
3.8326871395111084 to get symmetries
{'edges_cut': 60, 'edges_not_cut': -28, 'symmetries_inside': 24, 'symmetries_outside': 46080, 'struct_inside': ((3, 32), (2, 6), (4, 2), (1, 4)), 'struct_outside': ((6, 20), (4, 6), (3, 32), (5, 4), (2, 2))}
1  planes
([3, 3, 3, 1, 1, -4, 0],)
3774.415102005005 to get intersected edges
3.8973097801208496 to get symmetries
{'edges_cut': 60, 'edges_not_cut': -28, 'symmetries_inside': 96, 'symmetries_outside': 46080, 'struct_inside': ((3, 24), (4, 6), (2, 6), (1, 12)), 'struct_outside': ((3, 24), (6, 16), (4, 6), (5, 12), (2, 6))}
1  planes
([-1, -1, -1, 3, 3, 6, 0],)
3778.312814950943 to get intersected edges
4.3028364181518555 to get symmetries
{'edges_cut': 52, 'edges_not_cut': -20, 'symmetries_inside': 72, 'symmetries_outside': 46080, 'struct_inside': ((4, 6), (3, 6), (1, 26), (2, 18)), 'struct_outside': ((6, 8), (4, 18), (5, 26), (3, 6), (2, 6))}
1  planes
([3, 3, 3, 1, 1, 8, 0],)
3782.6160655021667 to get intersected edges
4.637042284011841 to get symmetries
{'edges_cut': 48, 'edges_not_cut': -16, 'symmetries_inside': 96, 'symmetries_outside': 46080, 'struct_inside': ((2, 18), (4, 4), (3, 4), (1, 32)), 'struct_outside': ((5, 32), (3, 4), (4, 18), (6, 6), (2, 4))}
2  planes
([1, 1, 1, 3, 3, -4, 0], [-2, -2, -2, 3, 3, -1, 0])
3787.2537121772766 to get intersected edges
3.083475351333618 to get symmetries
{'edges_cut': 100, 'edges_not_cut': -68, 'symmetries_inside': 72, 'symmetries_outside': 1440, 'struct_inside': ((3, 14), (4, 14), (6, 2), (5, 12), (2, 14), (1, 2)), 'struct_outside': ((6, 6), (4, 14), (2, 14), (1, 12), (3, 14), (5, 2))}
2  planes
([1, 1, 1, 3, 3, -4, 0], [3, 3, 3, 1, 1, -4, 0])
3790.337856531143 to get intersected edges
2.4056179523468018 to get symmetries
{'edges_cut': 88, 'edges_not_cut': -56, 'symmetries_inside': 72, 'symmetries_outside': 72, 'struct_inside': ((6, 6), (4, 10), (3, 12), (5, 4), (2, 20), (1, 4)), 'struct_outside': ((4, 20), (6, 8), (5, 4), (3, 12), (2, 10), (1, 4))}
2  planes
([1, 1, 1, 3, 3, -4, 0], [-1, -1, -1, 3, 3, 6, 0])
3792.744143009186 to get intersected edges
6.717223882675171 to get symmetries
{'edges_cut': 88, 'edges_not_cut': -56, 'symmetries_inside': 46080, 'symmetries_outside': 46080, 'struct_inside': ((3, 38), (4, 8), (2, 12), (1, 6)), 'struct_outside': ((3, 38), (4, 12), (5, 6), (2, 8))}
2  planes
([1, 1, 1, 3, 3, -4, 0], [3, 3, 3, 1, 1, 8, 0])
3799.4619908332825 to get intersected edges

KeyboardInterrupt:

In [ ]:
import pandas as pd
import random, time

d=5

filename = f"symmetries_tracked_{d}.csv"

h_limit=10
b_limit=10

chance = .01

edge_set = set(get_hypercube_edges(d))
edges = len(edge_set)
rows=[]

i=0
next_i=1
for h_coef in combinations_with_replacement(range(h_limit),d):
    for b in range(b_limit):
        i+=1
        if i!=next_i:
            continue
        else: 
            next_i += random.randint(10,100)
        
        plane = h_coef+tuple([b])
        t_s = time.time()
        print(f"doing {plane}")
        intersected_edges = set(for_loop_hyperplane_intersection(plane, edge_set))
        non_intersected_edges = edge_set.difference(intersected_edges)

        vertices_in = get_vertex_set_from_edges(intersected_edges)
        vertices_out = get_vertex_set_from_edges(non_intersected_edges)
        if len(vertices_in)==0:
            continue
        t_int = time.time()
        print(f"{t_int-t_s} to get intersected edges")
        row_data = {"hyperplane": tuple(plane),
                   "edges_cut": len(intersected_edges),
                   "edges_not_cut": edges-len(intersected_edges),
                   "symmetries_inside": count_symmetries(vertices_in),
                   "symmetries_outside": count_symmetries(vertices_out),
                   "struct_inside": deg_seq(intersected_edges), 
                   "struct_outside": deg_seq(non_intersected_edges)}
        print(f"{time.time()-t_int} to get symmetries")
        print(row_data)
        rows.append(row_data)

sym_df = pd.DataFrame(rows)
#sym_df.to_csv(filename)
sym_df.head()